import { MigrationInterface, QueryRunner } from "typeorm";

export class AddJSONFormatData1773080849410 implements MigrationInterface {
    name = 'AddJSONFormatData1773080849410'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`IDX_95b76af812bcd51f0e180126ed\` ON \`organizer\``);
        await queryRunner.query(`DROP INDEX \`IDX_3dd7c6e89c59e847a559aa620b\` ON \`tournament_formats\``);
        await queryRunner.query(`DROP INDEX \`IDX_26dfc3b9107ad9a8766523a41d\` ON \`bracket\``);
        await queryRunner.query(`ALTER TABLE \`team\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`tournament_formats\` ADD \`format_data\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_368e146b785b574f42ae9e53d5e\``);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`roleId\` \`roleId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`permissions\` DROP COLUMN \`module_access\``);
        await queryRunner.query(`ALTER TABLE \`permissions\` ADD \`module_access\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`organizer\` DROP FOREIGN KEY \`FK_95b76af812bcd51f0e180126ed1\``);
        await queryRunner.query(`ALTER TABLE \`organizer\` CHANGE \`name\` \`name\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organizer\` CHANGE \`email\` \`email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organizer\` CHANGE \`phone\` \`phone\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organizer\` CHANGE \`website\` \`website\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organizer\` CHANGE \`tournamentId\` \`tournamentId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`team_member\` DROP FOREIGN KEY \`FK_74da8f612921485e1005dc8e225\``);
        await queryRunner.query(`ALTER TABLE \`team_member\` CHANGE \`position\` \`position\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`team_member\` CHANGE \`jerseyNumber\` \`jerseyNumber\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`team_member\` CHANGE \`teamId\` \`teamId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`team\` CHANGE \`shortName\` \`shortName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`team\` CHANGE \`logoUrl\` \`logoUrl\` longtext NULL`);
        await queryRunner.query(`ALTER TABLE \`team\` CHANGE \`teamType\` \`teamType\` enum ('Club', 'School', 'College', 'Corporate', 'Academy') NULL`);
        await queryRunner.query(`ALTER TABLE \`team\` CHANGE \`city\` \`city\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`team\` CHANGE \`state\` \`state\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`team\` CHANGE \`country\` \`country\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`team\` CHANGE \`foundedYear\` \`foundedYear\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`team\` CHANGE \`homeGround\` \`homeGround\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`team\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`team\` CHANGE \`captainName\` \`captainName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`team\` CHANGE \`contactEmail\` \`contactEmail\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament_team\` DROP FOREIGN KEY \`FK_a57753f0e48a8681c0b2163ed12\``);
        await queryRunner.query(`ALTER TABLE \`tournament_team\` DROP FOREIGN KEY \`FK_e7ea12e2d49a7f5e6e1481429a1\``);
        await queryRunner.query(`ALTER TABLE \`tournament_team\` CHANGE \`tournamentId\` \`tournamentId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament_team\` CHANGE \`teamId\` \`teamId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament_tiebreakers\` DROP FOREIGN KEY \`FK_e98f04e20fe72b54149b835e1a3\``);
        await queryRunner.query(`ALTER TABLE \`tournament_tiebreakers\` CHANGE \`tournament_format_id\` \`tournament_format_id\` bigint NULL`);
        await queryRunner.query(`ALTER TABLE \`format_group_settings\` DROP FOREIGN KEY \`FK_2430af46e79fe7b31db940e423d\``);
        await queryRunner.query(`ALTER TABLE \`format_group_settings\` CHANGE \`format_id\` \`format_id\` bigint NULL`);
        await queryRunner.query(`ALTER TABLE \`format_knockout_settings\` DROP FOREIGN KEY \`FK_db7dce2ec50f4128929f6e8defc\``);
        await queryRunner.query(`ALTER TABLE \`format_knockout_settings\` CHANGE \`format_id\` \`format_id\` bigint NULL`);
        await queryRunner.query(`ALTER TABLE \`format_stages\` DROP FOREIGN KEY \`FK_e1b6cacec2f7bc359e1a2ff9c2d\``);
        await queryRunner.query(`ALTER TABLE \`format_stages\` CHANGE \`format_id\` \`format_id\` bigint NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament_formats\` DROP FOREIGN KEY \`FK_3dd7c6e89c59e847a559aa620bc\``);
        await queryRunner.query(`ALTER TABLE \`tournament_formats\` CHANGE \`tournament_id\` \`tournament_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`group_teams\` DROP FOREIGN KEY \`FK_6e9057760268c61106d216deae0\``);
        await queryRunner.query(`ALTER TABLE \`group_teams\` DROP FOREIGN KEY \`FK_578cb7280cd7810fa10041d1ea8\``);
        await queryRunner.query(`ALTER TABLE \`group_teams\` CHANGE \`group_id\` \`group_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`group_teams\` CHANGE \`team_id\` \`team_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`groups\` DROP FOREIGN KEY \`FK_a82fbc356b660aad77d4698babd\``);
        await queryRunner.query(`ALTER TABLE \`groups\` DROP FOREIGN KEY \`FK_4eb470229d0d4a522c2da183d2a\``);
        await queryRunner.query(`ALTER TABLE \`groups\` CHANGE \`tournament_id\` \`tournament_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`groups\` CHANGE \`stage_id\` \`stage_id\` bigint NULL`);
        await queryRunner.query(`ALTER TABLE \`match_sources\` DROP FOREIGN KEY \`FK_2edea41c8aff5e24a2ed873490b\``);
        await queryRunner.query(`ALTER TABLE \`match_sources\` CHANGE \`match_id\` \`match_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`match\` DROP FOREIGN KEY \`FK_b096f0c0ca94610b3e77128500c\``);
        await queryRunner.query(`ALTER TABLE \`match\` DROP FOREIGN KEY \`FK_5caac1768e2f5b7b9c69b62090c\``);
        await queryRunner.query(`ALTER TABLE \`match\` DROP FOREIGN KEY \`FK_07f5b02809e195be415834ed78a\``);
        await queryRunner.query(`ALTER TABLE \`match\` DROP FOREIGN KEY \`FK_873d0b9da9a0f032d00fbfb89c1\``);
        await queryRunner.query(`ALTER TABLE \`match\` DROP FOREIGN KEY \`FK_c4771d1b75b824a92fd9bd2b545\``);
        await queryRunner.query(`ALTER TABLE \`match\` CHANGE \`round\` \`round\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`match\` CHANGE \`bracketPosition\` \`bracketPosition\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`match\` CHANGE \`tournamentId\` \`tournamentId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`match\` CHANGE \`homeTeamId\` \`homeTeamId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`match\` CHANGE \`awayTeamId\` \`awayTeamId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`match\` CHANGE \`stage_id\` \`stage_id\` bigint NULL`);
        await queryRunner.query(`ALTER TABLE \`match\` CHANGE \`group_id\` \`group_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament\` CHANGE \`participantType\` \`participantType\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament\` CHANGE \`minTeams\` \`minTeams\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament\` CHANGE \`regOpenDate\` \`regOpenDate\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament\` CHANGE \`regCloseDate\` \`regCloseDate\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament\` CHANGE \`playerLimit\` \`playerLimit\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament\` CHANGE \`squadSize\` \`squadSize\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament\` CHANGE \`shortName\` \`shortName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament\` CHANGE \`type\` \`type\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament\` CHANGE \`visibility\` \`visibility\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament\` CHANGE \`logo\` \`logo\` longtext NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament\` CHANGE \`coverImage\` \`coverImage\` longtext NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament\` CHANGE \`sponsors\` \`sponsors\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`bracket\` DROP FOREIGN KEY \`FK_26dfc3b9107ad9a8766523a41d8\``);
        await queryRunner.query(`ALTER TABLE \`bracket\` DROP FOREIGN KEY \`FK_4597833a962222ac0176ead0441\``);
        await queryRunner.query(`ALTER TABLE \`bracket\` DROP COLUMN \`structureData\``);
        await queryRunner.query(`ALTER TABLE \`bracket\` ADD \`structureData\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`bracket\` CHANGE \`tournamentId\` \`tournamentId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`bracket\` CHANGE \`stage_id\` \`stage_id\` bigint NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_368e146b785b574f42ae9e53d5e\` FOREIGN KEY (\`roleId\`) REFERENCES \`user_role\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organizer\` ADD CONSTRAINT \`FK_95b76af812bcd51f0e180126ed1\` FOREIGN KEY (\`tournamentId\`) REFERENCES \`tournament\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`team_member\` ADD CONSTRAINT \`FK_74da8f612921485e1005dc8e225\` FOREIGN KEY (\`teamId\`) REFERENCES \`team\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament_team\` ADD CONSTRAINT \`FK_a57753f0e48a8681c0b2163ed12\` FOREIGN KEY (\`tournamentId\`) REFERENCES \`tournament\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament_team\` ADD CONSTRAINT \`FK_e7ea12e2d49a7f5e6e1481429a1\` FOREIGN KEY (\`teamId\`) REFERENCES \`team\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament_tiebreakers\` ADD CONSTRAINT \`FK_e98f04e20fe72b54149b835e1a3\` FOREIGN KEY (\`tournament_format_id\`) REFERENCES \`tournament_formats\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`format_group_settings\` ADD CONSTRAINT \`FK_2430af46e79fe7b31db940e423d\` FOREIGN KEY (\`format_id\`) REFERENCES \`tournament_formats\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`format_knockout_settings\` ADD CONSTRAINT \`FK_db7dce2ec50f4128929f6e8defc\` FOREIGN KEY (\`format_id\`) REFERENCES \`tournament_formats\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`format_stages\` ADD CONSTRAINT \`FK_e1b6cacec2f7bc359e1a2ff9c2d\` FOREIGN KEY (\`format_id\`) REFERENCES \`tournament_formats\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament_formats\` ADD CONSTRAINT \`FK_3dd7c6e89c59e847a559aa620bc\` FOREIGN KEY (\`tournament_id\`) REFERENCES \`tournament\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`group_teams\` ADD CONSTRAINT \`FK_6e9057760268c61106d216deae0\` FOREIGN KEY (\`group_id\`) REFERENCES \`groups\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`group_teams\` ADD CONSTRAINT \`FK_578cb7280cd7810fa10041d1ea8\` FOREIGN KEY (\`team_id\`) REFERENCES \`team\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`groups\` ADD CONSTRAINT \`FK_a82fbc356b660aad77d4698babd\` FOREIGN KEY (\`tournament_id\`) REFERENCES \`tournament\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`groups\` ADD CONSTRAINT \`FK_4eb470229d0d4a522c2da183d2a\` FOREIGN KEY (\`stage_id\`) REFERENCES \`format_stages\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`match_sources\` ADD CONSTRAINT \`FK_2edea41c8aff5e24a2ed873490b\` FOREIGN KEY (\`match_id\`) REFERENCES \`match\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`match\` ADD CONSTRAINT \`FK_b096f0c0ca94610b3e77128500c\` FOREIGN KEY (\`tournamentId\`) REFERENCES \`tournament\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`match\` ADD CONSTRAINT \`FK_5caac1768e2f5b7b9c69b62090c\` FOREIGN KEY (\`homeTeamId\`) REFERENCES \`team\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`match\` ADD CONSTRAINT \`FK_07f5b02809e195be415834ed78a\` FOREIGN KEY (\`awayTeamId\`) REFERENCES \`team\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`match\` ADD CONSTRAINT \`FK_873d0b9da9a0f032d00fbfb89c1\` FOREIGN KEY (\`stage_id\`) REFERENCES \`format_stages\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`match\` ADD CONSTRAINT \`FK_c4771d1b75b824a92fd9bd2b545\` FOREIGN KEY (\`group_id\`) REFERENCES \`groups\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bracket\` ADD CONSTRAINT \`FK_26dfc3b9107ad9a8766523a41d8\` FOREIGN KEY (\`tournamentId\`) REFERENCES \`tournament\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bracket\` ADD CONSTRAINT \`FK_4597833a962222ac0176ead0441\` FOREIGN KEY (\`stage_id\`) REFERENCES \`format_stages\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`bracket\` DROP FOREIGN KEY \`FK_4597833a962222ac0176ead0441\``);
        await queryRunner.query(`ALTER TABLE \`bracket\` DROP FOREIGN KEY \`FK_26dfc3b9107ad9a8766523a41d8\``);
        await queryRunner.query(`ALTER TABLE \`match\` DROP FOREIGN KEY \`FK_c4771d1b75b824a92fd9bd2b545\``);
        await queryRunner.query(`ALTER TABLE \`match\` DROP FOREIGN KEY \`FK_873d0b9da9a0f032d00fbfb89c1\``);
        await queryRunner.query(`ALTER TABLE \`match\` DROP FOREIGN KEY \`FK_07f5b02809e195be415834ed78a\``);
        await queryRunner.query(`ALTER TABLE \`match\` DROP FOREIGN KEY \`FK_5caac1768e2f5b7b9c69b62090c\``);
        await queryRunner.query(`ALTER TABLE \`match\` DROP FOREIGN KEY \`FK_b096f0c0ca94610b3e77128500c\``);
        await queryRunner.query(`ALTER TABLE \`match_sources\` DROP FOREIGN KEY \`FK_2edea41c8aff5e24a2ed873490b\``);
        await queryRunner.query(`ALTER TABLE \`groups\` DROP FOREIGN KEY \`FK_4eb470229d0d4a522c2da183d2a\``);
        await queryRunner.query(`ALTER TABLE \`groups\` DROP FOREIGN KEY \`FK_a82fbc356b660aad77d4698babd\``);
        await queryRunner.query(`ALTER TABLE \`group_teams\` DROP FOREIGN KEY \`FK_578cb7280cd7810fa10041d1ea8\``);
        await queryRunner.query(`ALTER TABLE \`group_teams\` DROP FOREIGN KEY \`FK_6e9057760268c61106d216deae0\``);
        await queryRunner.query(`ALTER TABLE \`tournament_formats\` DROP FOREIGN KEY \`FK_3dd7c6e89c59e847a559aa620bc\``);
        await queryRunner.query(`ALTER TABLE \`format_stages\` DROP FOREIGN KEY \`FK_e1b6cacec2f7bc359e1a2ff9c2d\``);
        await queryRunner.query(`ALTER TABLE \`format_knockout_settings\` DROP FOREIGN KEY \`FK_db7dce2ec50f4128929f6e8defc\``);
        await queryRunner.query(`ALTER TABLE \`format_group_settings\` DROP FOREIGN KEY \`FK_2430af46e79fe7b31db940e423d\``);
        await queryRunner.query(`ALTER TABLE \`tournament_tiebreakers\` DROP FOREIGN KEY \`FK_e98f04e20fe72b54149b835e1a3\``);
        await queryRunner.query(`ALTER TABLE \`tournament_team\` DROP FOREIGN KEY \`FK_e7ea12e2d49a7f5e6e1481429a1\``);
        await queryRunner.query(`ALTER TABLE \`tournament_team\` DROP FOREIGN KEY \`FK_a57753f0e48a8681c0b2163ed12\``);
        await queryRunner.query(`ALTER TABLE \`team_member\` DROP FOREIGN KEY \`FK_74da8f612921485e1005dc8e225\``);
        await queryRunner.query(`ALTER TABLE \`organizer\` DROP FOREIGN KEY \`FK_95b76af812bcd51f0e180126ed1\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_368e146b785b574f42ae9e53d5e\``);
        await queryRunner.query(`ALTER TABLE \`bracket\` CHANGE \`stage_id\` \`stage_id\` bigint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`bracket\` CHANGE \`tournamentId\` \`tournamentId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`bracket\` DROP COLUMN \`structureData\``);
        await queryRunner.query(`ALTER TABLE \`bracket\` ADD \`structureData\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`bracket\` ADD CONSTRAINT \`FK_4597833a962222ac0176ead0441\` FOREIGN KEY (\`stage_id\`) REFERENCES \`format_stages\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bracket\` ADD CONSTRAINT \`FK_26dfc3b9107ad9a8766523a41d8\` FOREIGN KEY (\`tournamentId\`) REFERENCES \`tournament\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament\` CHANGE \`sponsors\` \`sponsors\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tournament\` CHANGE \`coverImage\` \`coverImage\` longtext NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tournament\` CHANGE \`logo\` \`logo\` longtext NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tournament\` CHANGE \`visibility\` \`visibility\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tournament\` CHANGE \`type\` \`type\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tournament\` CHANGE \`shortName\` \`shortName\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tournament\` CHANGE \`squadSize\` \`squadSize\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tournament\` CHANGE \`playerLimit\` \`playerLimit\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tournament\` CHANGE \`regCloseDate\` \`regCloseDate\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tournament\` CHANGE \`regOpenDate\` \`regOpenDate\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tournament\` CHANGE \`minTeams\` \`minTeams\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tournament\` CHANGE \`participantType\` \`participantType\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tournament\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`match\` CHANGE \`group_id\` \`group_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`match\` CHANGE \`stage_id\` \`stage_id\` bigint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`match\` CHANGE \`awayTeamId\` \`awayTeamId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`match\` CHANGE \`homeTeamId\` \`homeTeamId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`match\` CHANGE \`tournamentId\` \`tournamentId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`match\` CHANGE \`bracketPosition\` \`bracketPosition\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`match\` CHANGE \`round\` \`round\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`match\` ADD CONSTRAINT \`FK_c4771d1b75b824a92fd9bd2b545\` FOREIGN KEY (\`group_id\`) REFERENCES \`groups\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`match\` ADD CONSTRAINT \`FK_873d0b9da9a0f032d00fbfb89c1\` FOREIGN KEY (\`stage_id\`) REFERENCES \`format_stages\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`match\` ADD CONSTRAINT \`FK_07f5b02809e195be415834ed78a\` FOREIGN KEY (\`awayTeamId\`) REFERENCES \`team\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`match\` ADD CONSTRAINT \`FK_5caac1768e2f5b7b9c69b62090c\` FOREIGN KEY (\`homeTeamId\`) REFERENCES \`team\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`match\` ADD CONSTRAINT \`FK_b096f0c0ca94610b3e77128500c\` FOREIGN KEY (\`tournamentId\`) REFERENCES \`tournament\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`match_sources\` CHANGE \`match_id\` \`match_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`match_sources\` ADD CONSTRAINT \`FK_2edea41c8aff5e24a2ed873490b\` FOREIGN KEY (\`match_id\`) REFERENCES \`match\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`groups\` CHANGE \`stage_id\` \`stage_id\` bigint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`groups\` CHANGE \`tournament_id\` \`tournament_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`groups\` ADD CONSTRAINT \`FK_4eb470229d0d4a522c2da183d2a\` FOREIGN KEY (\`stage_id\`) REFERENCES \`format_stages\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`groups\` ADD CONSTRAINT \`FK_a82fbc356b660aad77d4698babd\` FOREIGN KEY (\`tournament_id\`) REFERENCES \`tournament\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`group_teams\` CHANGE \`team_id\` \`team_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`group_teams\` CHANGE \`group_id\` \`group_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`group_teams\` ADD CONSTRAINT \`FK_578cb7280cd7810fa10041d1ea8\` FOREIGN KEY (\`team_id\`) REFERENCES \`team\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`group_teams\` ADD CONSTRAINT \`FK_6e9057760268c61106d216deae0\` FOREIGN KEY (\`group_id\`) REFERENCES \`groups\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament_formats\` CHANGE \`tournament_id\` \`tournament_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tournament_formats\` ADD CONSTRAINT \`FK_3dd7c6e89c59e847a559aa620bc\` FOREIGN KEY (\`tournament_id\`) REFERENCES \`tournament\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`format_stages\` CHANGE \`format_id\` \`format_id\` bigint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`format_stages\` ADD CONSTRAINT \`FK_e1b6cacec2f7bc359e1a2ff9c2d\` FOREIGN KEY (\`format_id\`) REFERENCES \`tournament_formats\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`format_knockout_settings\` CHANGE \`format_id\` \`format_id\` bigint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`format_knockout_settings\` ADD CONSTRAINT \`FK_db7dce2ec50f4128929f6e8defc\` FOREIGN KEY (\`format_id\`) REFERENCES \`tournament_formats\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`format_group_settings\` CHANGE \`format_id\` \`format_id\` bigint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`format_group_settings\` ADD CONSTRAINT \`FK_2430af46e79fe7b31db940e423d\` FOREIGN KEY (\`format_id\`) REFERENCES \`tournament_formats\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament_tiebreakers\` CHANGE \`tournament_format_id\` \`tournament_format_id\` bigint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tournament_tiebreakers\` ADD CONSTRAINT \`FK_e98f04e20fe72b54149b835e1a3\` FOREIGN KEY (\`tournament_format_id\`) REFERENCES \`tournament_formats\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament_team\` CHANGE \`teamId\` \`teamId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tournament_team\` CHANGE \`tournamentId\` \`tournamentId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tournament_team\` ADD CONSTRAINT \`FK_e7ea12e2d49a7f5e6e1481429a1\` FOREIGN KEY (\`teamId\`) REFERENCES \`team\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament_team\` ADD CONSTRAINT \`FK_a57753f0e48a8681c0b2163ed12\` FOREIGN KEY (\`tournamentId\`) REFERENCES \`tournament\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`team\` CHANGE \`contactEmail\` \`contactEmail\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`team\` CHANGE \`captainName\` \`captainName\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`team\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`team\` CHANGE \`homeGround\` \`homeGround\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`team\` CHANGE \`foundedYear\` \`foundedYear\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`team\` CHANGE \`country\` \`country\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`team\` CHANGE \`state\` \`state\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`team\` CHANGE \`city\` \`city\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`team\` CHANGE \`teamType\` \`teamType\` enum ('Club', 'School', 'College', 'Corporate', 'Academy') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`team\` CHANGE \`logoUrl\` \`logoUrl\` longtext NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`team\` CHANGE \`shortName\` \`shortName\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`team_member\` CHANGE \`teamId\` \`teamId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`team_member\` CHANGE \`jerseyNumber\` \`jerseyNumber\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`team_member\` CHANGE \`position\` \`position\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`team_member\` ADD CONSTRAINT \`FK_74da8f612921485e1005dc8e225\` FOREIGN KEY (\`teamId\`) REFERENCES \`team\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organizer\` CHANGE \`tournamentId\` \`tournamentId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`organizer\` CHANGE \`website\` \`website\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`organizer\` CHANGE \`phone\` \`phone\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`organizer\` CHANGE \`email\` \`email\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`organizer\` CHANGE \`name\` \`name\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`organizer\` ADD CONSTRAINT \`FK_95b76af812bcd51f0e180126ed1\` FOREIGN KEY (\`tournamentId\`) REFERENCES \`tournament\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`permissions\` DROP COLUMN \`module_access\``);
        await queryRunner.query(`ALTER TABLE \`permissions\` ADD \`module_access\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`roleId\` \`roleId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_368e146b785b574f42ae9e53d5e\` FOREIGN KEY (\`roleId\`) REFERENCES \`user_role\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament_formats\` DROP COLUMN \`format_data\``);
        await queryRunner.query(`ALTER TABLE \`team\` ADD \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_26dfc3b9107ad9a8766523a41d\` ON \`bracket\` (\`tournamentId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_3dd7c6e89c59e847a559aa620b\` ON \`tournament_formats\` (\`tournament_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_95b76af812bcd51f0e180126ed\` ON \`organizer\` (\`tournamentId\`)`);
    }

}
